matrix:
  include:
    - language: node_js
      node_js:
        - "8.12.0"
      script:
        - yarn install

    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services: mysql
      test:
        adapter: mysql
        database: ticketx
        username: root
        encoding: utf8
      env: 
      global:
        - BUILD_ON_TRAVIS=true
      matrix:
        - DJANGO=2.1.2 DB=mysql
      branches:
      only:
        - /.*/
      cache:
        yarn: true
      install: 
        - pip install pipenv
        - pipenv run pip install pip==18.0
        - pipenv install --dev --deploy
        - cd server
      script: 
        - python manage.py test --settings=project.settings.prod
