language: python
dist: xenial
sudo: required
python: "3.7"
services: mysql
test:
  adapter: mysql
  database: ticketx
  username: root
  encoding: utf8
env: 
  global:
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=2.1.2 DB=mysql
branches:
  only:
  - master
  - travis-ci-update
  - database-ci
cache:
  yarn: true
before_script:
  - sudo mysql -e 'create database IF NOT EXISTS ticketx;' -uroot
  - sudo mysql -e 'GRANT ALL PRIVILEGES ON *.* to 'root'@'localhost';' -uroot
  - python manage.py migrate
install: 
  - pip install pipenv
  - pipenv run pip install pip==18.0
  - pipenv install --dev --deploy
  - cd server
script: 
  - python manage.py test
