language: python
dist: xenial
sudo: required
python: "3.7"
services: mysql
test:
  adapter: mysql
  database: ticketx
  username: root
  encoding: utf8
env: 
  - DJANGO=2.1.2 DB=mysql
branches:
  only:
  - master
  - travis-ci-update
  - database-ci
cache:
  yarn: true
install: 
  - pip install pipenv
  - pipenv run pip install pip==18.0
  - pipenv install --dev --deploy
  - cd server
script: 
  - python manage.py test
