image: Visual Studio 2017

platform:
  - x64
environment:
  matrix:
    - PYTHON: "C:\\Python37"
      DJANGOVER: 1.11.3
      PYTHON_ARCH: "32"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - pip install -U Django
  - pip install pipenv
  - pipenv run pip install pip==18.0
  - pipenv install --dev --deploy

build_script:
  - ps: cd server

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - python manage.py migrate --run-syncdb
