image: Visual Studio 2017

platform:
  - x64
environment:
  matrix:
    - PYTHON: "C:\\Python37"
      DJANGOVER: 2.1.2
      PYTHON_ARCH: "32"

install:
  - pip install pipenv
  - pip install Django==2.1.2
  - pipenv lock
  - pipenv install --dev --deploy 

build_script:
  - ps: cd server

test_script:
  - python manage.py migrate
