image: Visual Studio 2017

platform:
  - x64
environment:
  matrix:
    - PYTHON: "C:\\Python37"
      DJANGOVER: 1.11.3
      PYTHON_ARCH: "32"

install:
  - pip install -U Django
  - pip install pipenv
  - pipenv lock
  - pipenv install --dev --deploy 

build_script:
  - ps: cd server

test_script:
  - python manage.py migrate
